apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-intexcel-com-tls
spec:
  secretName: k8s-multi-intexcel-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.intexcel.com
  dnsNames: 
    - multi-k8s.intexcel.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.intexcel.com
      

